### ISSUE TITLE
`FormatException` from `BitmapFont.LoadXml` in some locales

### ISSUE THREAD

**Issue by YoshiRulz** [cyotek/Cyotek.Drawing.BitmapFont#25]
Repro:
`mkdir repro-25 && cd repro-25 && dotnet new console && dotnet add package Cyotek.Drawing.BitmapFont -v 2.0.1`
Then edit `Program.cs` to:
```csharp
using System;
using System.IO;

using Cyotek.Drawing.BitmapFont;

using var fs = File.OpenRead("./courier16px.fnt");
BitmapFont font = new();
font.LoadXml(fs);
Console.WriteLine("success");
```
Download [this file](https://github.com/TASVideos/BizHawk/blob/2.6.1/src/BizHawk.Client.EmuHawk/Resources/courier16px.fnt) (`curl -O https://raw.githubusercontent.com/TASVideos/BizHawk/2.6.1/src/BizHawk.Client.EmuHawk/Resources/courier16px.fnt`).
Finally, `dotnet run`. On Windows with the default en-AU locale (and presumably most others), you get:
```
success
```
But change this setting:
![screenshot](https://user-images.githubusercontent.com/13409956/115487853-dfe72f00-a29c-11eb-8a10-99b3823bcfe9.png)
...and run again, and you get:
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Cyotek.Drawing.BitmapFont.BitmapFont.LoadXml(TextReader reader)
   at Cyotek.Drawing.BitmapFont.BitmapFont.LoadXml(Stream stream)
   at <Program>$.<Main>$(String[] args)
```

Probable cause: I think all these calls to `Convert.ToInt32` need to have [`CultureInfo.InvariantCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-5.0) as the second argument.
https://github.com/cyotek/Cyotek.Drawing.BitmapFont/blob/dd44d7dc471941b4e56a7a0316031419e3201a8f/src/BitmapFont.cs#L814-L836

**Comment by cyotek** [comment]
Hello,

Thanks very much for reporting this rather than an insulting comment in an issue I wouldn't normally see.

You were correct in your assessment of `Convert.ToInt32` being the cause, testing also indicated additional calls to `int.Parse` and `int.TryParse` which needed addressing too.

I've pushed version 2.0.2 with this fix in place - please give a whirl and let me know if you encounter future issues.

Thanks again for the bug report and repro steps!

Regards;
Richard Moss
